### ISSUE TITLE
Not decrypting

### ISSUE THREAD

**Issue by lgariv** [shinvou/decrypt0r#1]
iPhone X 10,6
iOS 13.1

The tool creates 2 folders; Unencrypted and decrypted. However it just drops all of the files to unencrypted without decrypting anything. Re-running it does nothing.

(img4 and partialzip both working and placed in /usr/local/bin which is already exported to $PATH)

**Comment by shinvou** [comment]
You probably don't have img4 installed, do you?

**Comment by shinvou** [comment]
It seems that there's no keybag returned. Can you verify by inserting print(keybag) and rerun?

**Comment by lgariv** [comment]
> It seems that there's no keybag returned. Can you verify by inserting print(keybag) and rerun?

where to insert it?

**Comment by shinvou** [comment]
Line 46.
But since I already check the returned string, it has to be empty. What OS are you running this on?

**Comment by lgariv** [comment]
> Line 46.
> But since I already check the returned string, it has to be empty. What OS are you running this on?

MacOS Catalina beta. And just checked it too and I think it looks fine, can't understand why it wouldn't work 😒

**Comment by lgariv** [comment]
I think I just found the problem! recompiled newest partialzip and img4lib and copied partialzip and img4 to /usr/local/bin
I guess that it was img4 because the script did in fact extracted the images. Strange tho because img4 command on it's own was working.

**Comment by shinvou** [comment]
Ok, glad to hear that it works now. Closing then.
