### ISSUE TITLE
Path to ipwndfu should be parsed from cmd.

### ISSUE THREAD

**Issue by krisanovdev** [shinvou/decrypt0r#2]
Subj.

**Comment by shinvou** [comment]
Why?

**Comment by krisanovdev** [comment]
Why do we need to hardcode it? It is better to imlpement it as cmd argument for better automation stuff.

**Comment by shinvou** [comment]
Should I parse other needed tools from args too then? Like img4 and libirecovery?

**Comment by krisanovdev** [comment]
Its okay to have such tools in PATH

**Comment by shinvou** [comment]
Good to know.
